### ISSUE TITLE
Activity to Fragment

### ISSUE THREAD

**Issue by SJ-Lee33** [Nicer-since-2021/attiary-android#17]
`ActivityToFragment` branch를 생성해 두었다.
activity 구성을 fragment구성으로 바꾸는 작업은 `main`이 아니라 `dev` 브랜치에서 하도록 하자. 
혹시 모르니 main은 이 이슈가 마무리될 때까지 동결해 두면 좋겠다.
각자 ActivityToFragment 브랜치를 pull해서 아래의 작업을 완료하고 dev 브랜치에 PR 하면 된다.

# 리팩토링 목적
ready, main, write 세가지 디렉토리에 각각 액티비티를 깔고, 프래그먼트를 구현해 연결한다.

# ActivityToFragment에 구현한 것
1. ready, main, write 세가지 디렉토리에 각각 `ReadyActivity.kt`, `MainActivity2.kt`, `WriteActivity`를 생성했다.
(Activity→Fragment로 모두 옮기고 나면 MainActivity2를 MainActivity로 변경할 예정이다)
2. 프래그먼트 xml에서도 가능한 한 ConstaintLayout을 사용했다.
3. 현재까지 구현되어있는 액티비티의 xml을 프래그먼트 xml로 복사해 두었다. (activity_app_password 제외)
4. `ReadyActivity.kt`에 `SplashFragment.kt`를 연결해 두었다. `MainActivity.kt` 에서 'Fragment 구성으로 보기' 버튼 클릭하면 `ReadyActivity.kt`로 이동한다.

# 앞으로 할 일
- 각자 액티비티에 구현했던 기능을 프래그먼트에도 구현하고,
- 기능까지 완성된 프래그먼트를 적절한 액티비티에 연결해야 한다.
- 액티비티를 프래그먼트로 모두 옮기면, 기존의 엑티비티는 삭제한다.

**Comment by S00MIN-KIM** [comment]
**회의 결과**
프래그먼트로 작업하려는 이유: 시그니처 음악을 끊이지 않고 재생시키기 위해서
현재까지 작업한 액티비티는 대부분 해당되지 않으므로 옮겨야 하는 이유가 없는 것으로 확인. (setting 관련만 수정 필요)
다만, 앞으로의 작업에 해당되는 메인 기능들은 프래그먼트를 활용하여 개발해야 한다.
