### ISSUE TITLE
warning about a crash caused by DB version change

### ISSUE THREAD

**Issue by S00MIN-KIM** [Nicer-since-2021/attiary-android#36]
#32 에서 DB 구조를 변경하였기 때문에 이전 버전의 데이터가 기기 혹은 에뮬레이터에 남아있다면 버전 충돌이 일어날 수 있습니다. 
따라서 캐시 및 데이터 삭제를 한 후에 이후 버전을 이용해주시기 바랍니다!

**Comment by hoit1302** [comment]
덕분에 해결했습니다 ~~
